#header
name: AC
description: AC的个人分享
favicon: /favicon.ico
ga: ''

#nav
nav:
    HOME: /
    ARCHIVE: /archives/
    # GALLERY:  /gallery/
    # ABOUT: /about/

#post
excerpt_link: 阅读全文


#about me
aboutMeImg: /about_me.png

github: https://github.com/acr1mony

#copyright
themeLink: https://github.com/yiliashaw/hexo-theme-prince

